[package]
name = "app"
version = "0.1.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { path = "./lib/Rocket/core/lib", features = ["json","tls"] }
ws = { package = "rocket_ws", path = "./lib/Rocket/contrib/ws" }
serde = { version = "1.0.164", features = ["derive"] }
rust-embed = "6.7.0"
toml = "0.7.5"
tokio-tungstenite = "0.19.0"
