[package]
name = "app"
version = "0.1.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "=0.5.0-rc.3", features = ["json","tls"] }
serde = { version = "1.0.171", features = ["derive"] }
rust-embed = "6.8.1"
shell-words = "1.1.0"
toml = "0.7.6"