[package]
name = "untitled"
version = "0.2.3"
edition = "2021"
authors = ["Brian gutierrez <luzmsara77@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { path = "./lib/Rocket/core/lib", features = ["json","tls"] }
ws = { package = "rocket_ws", path = "./lib/Rocket/contrib/ws" }
serde = { version = "1.0.183", features = ["derive"] }
clap = { version = "4.3.21", features = ["derive"] }
serde_json = "1.0.104"
shlex = "1.1.0"
